CREATE TABLE POLICE(
P_ID NUMBER(3) NOT NULL,
F_NAME VARCHAR2(10) NOT NULL,
L_NAME VARCHAR2(10),
PHONE_NO VARCHAR2(11) NOT NULL,
P_STATION VARCHAR2(30) NOT NULL,
ADDRESS VARCHAR2(100) NOT NULL,
CONSTRAINT P_ID_UK UNIQUE(P_ID),
CONSTRAINT PHONE_NO_UK UNIQUE(PHONE_NO));

CREATE TABLE CRIMINAL(
CR_ID NUMBER(5) NOT NULL,
F_NAME VARCHAR2(10) NOT NULL,
L_NAME VARCHAR2(10),
AGE NUMBER(3) CHECK (AGE >= 6 AND AGE <= 100) NOT NULL,
GENDER VARCHAR2(6) NOT NULL,
PHONE_NO VARCHAR2(11) NOT NULL,
ADDRESS VARCHAR2(100) NOT NULL,
CONSTRAINT CR_ID_UK UNIQUE(CR_ID),
CONSTRAINT CRPHONE_NO_UK UNIQUE(PHONE_NO));

CREATE TABLE CRIME(
CASE_ID NUMBER(5) NOT NULL,
CRIME_TYPE VARCHAR2(25) NOT NULL,
CR_ID NUMBER(5) NOT NULL,
POLICE_ID NUMBER(5) NOT NULL,
CRIME_DATE DATE NOT NULL,
CONSTRAINT CR_CRIME_ID_UK UNIQUE(CR_ID),
CONSTRAINT CASE_ID_UK UNIQUE(CASE_ID));

CREATE TABLE JAIL(
JAIL_ID NUMBER(5) NOT NULL,
CR_ID NUMBER(5) NOT NULL,
JAIL_NAME VARCHAR2(25) NOT NULL,
SENTENCE_TIME VARCHAR2(10) NOT NULL,
CONSTRAINT CR_J_ID_UK UNIQUE(CR_ID),
CONSTRAINT J_ID_UK UNIQUE(JAIL_ID));

CREATE TABLE HOSPRECORD(
HOSP_ID NUMBER(5) NOT NULL,
CR_ID NUMBER(5) NOT NULL,
HEIGHT VARCHAR2(10) NOT NULL,
WEIGHT VARCHAR2(10) NOT NULL,
BLOODGRP VARCHAR2(7) NOT NULL,
IDENTIFICATION VARCHAR2(20) NOT NULL,
CONSTRAINT CR_HR_ID_UK UNIQUE(CR_ID),
CONSTRAINT H_ID_UK UNIQUE(HOSP_ID));

CREATE TABLE ADMIN(
ADMIN_ID NUMBER(1) CHECK (ADMIN_ID <= 3) NOT NULL,
USERNAME VARCHAR2(15) NOT NULL,
PASSWORD VARCHAR2(15) NOT NULL,
PASSWD_HINT VARCHAR2(15) NOT NULL,
CONSTRAINT USER_NAME_UK UNIQUE (USERNAME),
CONSTRAINT ADM_ID_UK UNIQUE(ADMIN_ID));

INSERT INTO ADMIN
VALUES(1, 'admin', 'nopasswd', 'No Password');

COMMIT;